// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel DrawIndexTexture

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> _LightIndexTex;
float3 _LightIndexTex_Size;


[numthreads(8,8,1)]
void DrawIndexTexture (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    _LightIndexTex[id.xy] = 1;
}
